package-lock.json
package.json
src/CatalystClient.ts
src/ContentAPI.ts
src/ContentClient.ts
src/utils/DeploymentBuilder.ts
src/utils/Helper.ts
test/ContentClient.spec.ts
test/utils/DeploymentBuilder.spec.ts
test/utils/Helper.spec.ts

We are doing two things here:
1. We are adding new fetching methods that call the `/deployments` endpoint
2. We are using a global time API when creating new entities

feat: adding deployments fetching

---

.circleci/config.yml
package-lock.json
package.json
src/CatalystClient.ts
src/ContentAPI.ts
src/ContentClient.ts
test/ContentClient.spec.ts
tsconfig.json

We are adding deployment streaming to the catalyst client. This is mainly because the there are so many deployments that we would get an out of memory error if we tried to keep all the deployments in memory

feat: add deployments streaming

---

src/ContentClient.ts
src/utils/DeploymentBuilder.ts

We are doing two things on this PR:
The previous version of the code allowed deployments in NodeJs, but it didn't work when executed on the browser. Buffers and Blobs are not compatible, so we need to check and act accordingly
On the previous defined workflow, in order to build the entity itself, all files needed to be passed. The thing is, that if we are making a change on the metadata, the files may not change. In that case, we shouldn't force users to download the files and re-upload them. This is why we now expose `buildEntityWithAlreadyUploadedHashes`

fix: allow deployments in browser

---

src/utils/DeploymentBuilder.ts

We had a bug in `DeploymentBuilder#buildEntityWithoutNewFiles`, because we were sending the parameters to `DeploymentBuilder#buildEntityInternal` in the wrong order. It typed because `EntityMetadata` was of type `any`.

fix: parameter position bug

---

src/CatalystClient.ts
src/ContentAPI.ts
src/ContentClient.ts

Removes `fetchHistory` and `fetchFullHistory` methods from `ContentClient`.

refactor: remove getHistory from ContentClient

---

package-lock.json
package.json
src/CatalystClient.ts
src/ContentClient.ts
src/LambdasAPI.ts
src/LambdasClient.ts
src/utils/Helper.ts
test/LambdasClient.spec.ts
test/utils/Helper.spec.ts

We are mainly adding callers to the new collection endpoints:
* `/profiles`
* `/collections/wearables`
* `/collections/wearables-by-owner/:ethAddress`
In doing so, we refactored a lot of the logic that previously only applied to the `ContentClient`, and moved it to a helper, so that it could also be used by the `LambdasClient`

feat: add collection lambdas to client

---

package-lock.json
package.json
src/CatalystClient.ts
src/ContentAPI.ts
src/ContentClient.ts
test/ContentClient.spec.ts

Removing `originUrl` and `originTimestamp`.

breaking-change: remove getHistory and origin fields

---

src/CatalystClient.ts
src/ContentAPI.ts
src/ContentClient.ts
src/LambdasAPI.ts
src/LambdasClient.ts
test/ContentClient.spec.ts
test/LambdasClient.spec.ts

We are doing 2 changes in this PR. 
On one side, we are removing the `fetchProfile` method, since we will be deprecating that endpoint
On the other side, we are now making filters required when fetching or streaming deployments. This is to avoid certain calls to the content server that would fetch all existing deployments

[Breaking Change] fix: avoid very expensive calls to content server

---

src/CatalystAPI.ts
src/CatalystClient.ts
src/ContentAPI.ts
src/ContentClient.ts
src/LambdasAPI.ts
src/LambdasClient.ts

We are doing 2 things on this PR:
* Since clients can be created with a random catalyst, we are now exposing the catalyst/content/lambdas url
* We are making a fix to avoid an error we've seen: `ReferenceError: Blob is not defined`

fix: avoid blob error

---

src/ContentClient.ts
src/utils/Helper.ts
test/ContentClient.spec.ts

The idea is to use the deployments' local timestamp when handling pagination, instead of using the offset. This is so that the query is simpler to handle for the database. However, this will only be possible to do when the following two conditions are met:
* The field `auditInfo` is asked for in the request
* The sort by field is `localTimestamp` (or it isn't set, since `localTimestamp` is the default)
We are doing two big changes
1. We are using the local timestamp for pagination when possible
2. We are now exposing `QueryBuilders`. These are objects that help build final queries based on the base url and query parameters. They weren't exposed before, but since we want to be able to easily change the query params, it made sense to expose them

perf: use local timestamp instead of offset when possible

---

src/ContentClient.ts
src/utils/Helper.ts

In https://github.com/decentraland/catalyst-client/pull/75, we added the possibility to use local timestamp for pagination, instead of offset.
The problem was that we only added reserved space in the url `fromLocalTimestamp` and not `toLocalTimestamp`. So it would happen that there would be no space left in the url.
We are now making a fix for that, but we are also optimizing the way reserved space is calculated. We will be able to set a reserved space for multiple parameters, but when those parameters have a value set, then the reserved space won't be counted any more

fix: support multiple reserved parameters

---

src/utils/Helper.ts
test/LambdasClient.spec.ts
test/utils/Helper.spec.ts

We've made some changes in how the `/wearables` endpoint performs pagination. Previously, we had limit/offset. Now, we have a `next` property that provides the url necessary to navigate through remaining elements.
So in this PR, we are making the changes necessary to support this new way of iterating through all elements

fix: use pagination correctly in /wearables

---

package-lock.json
package.json
src/ContentClient.ts
src/utils/Helper.ts

We were using `isomorphic-form-data`, a library that only has 4 lines, to be able to use `FormData` both in Node and the browser. But we had forked it to change 2 of those 4 lines, so it was better to just do it directly on our library
This change has been tested in:
* CLI
* Explorer
* Catalyst

refactor: avoid isomorphic form data

---

src/ContentClient.ts

We need to send `toLocalTimestamp` and `fromLocalTimestamp` query parameters as we can't ensure that all the other catalyst have updated to the latest version that uses `from` and `to`.

Set legacy query params

---

package-lock.json
src/CatalystClient.ts
src/ContentClient.ts
test/ContentClient.spec.ts

Motivation:
Currently, the `DeploymentBuilder` is calling `worldtimeapi` when there isn't a timestamp provided, this is a problem since the API is unreliable (returns 503 more often than expected). Thus we're switching to depend on the timestamp provided by the catalyst peer that the client is connected to. 
Also, the DeploymentBuilder accepts a timestamp that might come with problems since the user can taint the information, the proposal is that in the future we stop exposing `DeploymentBuilder` and let the users only build deployments through the new exposed method in the clients
In this PR:
- Add method to build a deployment from the Catalyst client
- Add method to build a deployment from the Content client
Fixes #19

Add method to build entity from the catalyst and content client

---

src/utils/DeploymentBuilder.ts

We already added a way to reliably calculate the timestamp in https://github.com/decentraland/catalyst-client/pull/87, we just forgot to remove this code. The API we were using is unreliable, so there is no need to continue using it.

refactor: remove global time API

---

package-lock.json
package.json
src/ContentClient.ts
src/utils/DeploymentBuilder.ts
test/ContentClient.spec.ts
test/unit/DeploymentBuilder.spec.ts

Based on the usage of `buildEntityAndFile` across repositories what makes more sense is to assimilate that function inside the client.
The PR original's purpose was to upgrade the hashing algorithm to `CIDv1`. The assimilation of the function was necessary.
There is a second PR in `catalyst-commons` to remove the duplicated function https://github.com/decentraland/catalyst-commons/pull/168

BREAKING feat: use hashV1 and assimilate buildEntityAndFile from commons

---

src/CatalystClient.ts
src/ContentAPI.ts
src/ContentClient.ts
test/ContentClient.E2E.spec.ts
test/ContentClient.spec.ts

This PR will remove the unused functions from the shared catalyst client to lower complexity on the client side.
To address what needs to be removed here we used CodeSearch. Basically, we searched for those functions only being used on `catalyst/lambdas server` and moved their implementation to that project instead of having them in the shared client.
Since I don't have access to GitHub CodeSearch yet I would appreciate to double-check that the functions removed in this PR are only being used by this lambdas server mentioned above.
Off-note: the tests removed will be added to `catalyst` where the implementations will be.
[Issue (#1119)](https://github.com/decentraland/catalyst/issues/1119)

refactor: remove unused functions from shared client to lower complexity

---

.gitignore
package.json
src/client/utils/Helper.ts
tsconfig-build.json
tsconfig.json

This library package is being published wrongly because it adds the src directory to the build output. Therefore, this PR updates the library build output to avoid creating the `src` directory in build the output, so the clients can import the library like `import { buildEntity } from 'dcl-catalyst-client/dist/client/utils/DeploymentBuilder'` instead of `import { buildEntity } from 'dcl-catalyst-client/dist/src/client/utils/DeploymentBuilder'`
Before the update:
```
.
|____package.json
|____src
| |____types.js
| |____types.js.map
| |____types.d.ts
| |____contracts
| | |____abi.js.map
| | |____types.js
| | |____types.js.map
| | |____types.d.ts
| | |____index.js
| | |____index.js.map
| | |____abi.d.ts
| | |____index.d.ts
| | |____abi.js
| |____index.js
| |____index.js.map
| …
```

fix: build export

---

src/client/ContentClient.ts
src/client/LambdasClient.ts
src/client/utils/fetcher.ts
test/ContentClient.spec.ts

We need to include the x-requested-by header as allowed header in the server, but I'm not quite sure why is not included right now:
```
Access to XMLHttpRequest at 'https://peer-ap1.decentraland.zone/lambdas/profiles' from origin 'https://marketplace-qka1jpxj2-decentraland1.vercel.app/' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.
```

chore: remove default request headers

---

src/client/ContentClient.ts
test/ContentClient.spec.ts

This PR adds the functionality to prevent checks from happening when downloading content.

feat: Add the avoid checks functionality to the download content feature

---

src/client/utils/fetcher.ts

This PR introduces a fix on how requests to Catalyst are formatted when including a query parameter.
Current format example:
`https://<HOST>/lambdas/users/<ADDRESS>/namespageSize=1`
Expected format example:
`https://<HOST>/lambdas/users/<ADDRESS>/names?pageSize=1`

fix: query-params handling at fetcher
